name: power_pro_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  awesome_bottom_bar: ^1.2.4
  chewie: ^1.12.1
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_svg: ^2.1.0
  get_it: ^7.7.0
  image_picker: ^1.1.2
  shared_preferences: ^2.5.3
  slide_countdown: ^1.3.1
  video_player: ^2.10.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/videos/

  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Light.otf
          weight: 300
        - asset: assets/fonts/Satoshi-Regular.otf
          weight: 400
        - asset: assets/fonts/Satoshi-Medium.otf
          weight: 500
        - asset: assets/fonts/Satoshi-Bold.otf
          weight: 700
        - asset: assets/fonts/Satoshi-Black.otf
          weight: 900

        - asset: assets/fonts/Satoshi-LightItalic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/Satoshi-Italic.otf
          weight: 400
          style: italic
        - asset: assets/fonts/Satoshi-MediumItalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/Satoshi-BoldItalic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/Satoshi-BlackItalic.otf
          weight: 900
          style: italic
